calc logic and css
pacynek93/harbor-calc pull request #1
Opened 2023-09-17 15:37 UTC by pacynek93

2023-09-17 17:08 UTC, DMTcorp requested changes

2023-09-17 17:08 UTC, DMTcorp commented on src/components/Buttons/Buttons.js
> +      </div>
Use `Array.map()` here

2023-09-17 17:08 UTC, DMTcorp commented on src/components/Screen/Screen.js
> +      <Buttons updateScreen={updateScreen} />
you can directly pass `setScreenContent` here

2023-09-18 17:10 UTC, oskarkasprzyk commented on src/components/Buttons/Buttons.js
Why use div selector instead button selector?
You use"operator" and "special" as css class but you didnt define it

2023-09-18 20:04 UTC, DMTcorp commented
1. The structure is a bit confusing, I would suggest something like that:
```
App
-- Screen (or Display)
-- Keyboard
-- -- Button 
```

2. I would also suggest to extract the calc logic to a different file
3. Use [Context](https://legacy.reactjs.org/docs/context.html) to avoid prop drilling

2023-09-20 13:45 UTC, oskarkasprzyk commented on src/components/Button/Button.js
> +    {button.value === "/" ? "÷" : button.value === "*" ? "x" : button.value}
Don't nest ternary expressions!

2023-09-20 13:45 UTC, oskarkasprzyk commented on src/components/Button/Button.js
> +const Button = ({ button, handleButtonClick }) => (
If you don't use prop-types or typescript, I would prefer remove button prop and make onClick + children + className props, it's more readable for other

2023-09-20 13:45 UTC, oskarkasprzyk commented on src/components/Keyboard/Keyboard.js
> +    { value: "7", className: "" },
Remove from array keys with empty value

2023-09-20 13:49 UTC, pacynek93 commented on src/components/Buttons/Buttons.js
done

2023-09-20 15:00 UTC, pacynek93 commented on src/components/Button/Button.js
> +    {button.value === "/" ? "÷" : button.value === "*" ? "x" : button.value}
Done, moved to Keyboard.js

2023-09-20 15:01 UTC, pacynek93 commented on src/components/Button/Button.js
> +const Button = ({ button, handleButtonClick }) => (
done

2023-09-20 15:01 UTC, pacynek93 commented on src/components/Wrapper/Wrapper.js
> +export default Wrapper;
Correct, component deleted

2023-09-20 15:15 UTC, oskarkasprzyk commented on src/components/Keyboard/Keyboard.js
> +        let buttonText;
Remove switch and make object like
`const MathOperatorMath = {
  '/': '÷',
  ...rest
}`

2023-09-21 16:37 UTC, pacynek93 commented on src/components/Keyboard/Keyboard.js
> +        let buttonText;
Ok refactored in last commit

2023-10-01 20:06 UTC, merged